### Login
POST http://localhost:4632/auth/login
Content-Type: application/json

{
  "username": "user1",
  "password": "password1"
}

> {% client.global.set("token", response.body.token) %}
> {%
    assert response.status === 200;
    assert response.body.token !== undefined;
%}

###

### Get All Todos
GET http://localhost:4632/todos
Authorization: Bearer {{token}}

> {%
    assert response.status === 200;
    assert Array.isArray(response.body);
%}

###

### Create a Todo
POST http://localhost:4632/todos
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userId": 1,
  "title": "New Todo",
  "completed": false
}

> {%
    assert response.status === 201;
    assert response.body.title === "New Todo";
%}

###

### Get User Profile
GET http://localhost:4632/users/1
Authorization: Bearer {{token}}

> {%
    assert response.status === 200;
    assert response.body.id === 1;
    assert response.body.username === "user1";
%}

